apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kvm-operator
rules:
  - apiGroups:
      - cluster.giantswarm.io
    resources:
      - kvmes
    verbs:
      - "*"
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - "*"
  - apiGroups:
      - extensions
    resources:
      - thirdpartyresources
    verbs:
      - "*"
  - apiGroups:
      - core.giantswarm.io
    resources:
      - storageconfigs
    verbs:
      - "*"
  - apiGroups:
      - provider.giantswarm.io
    resources:
      - kvmconfigs
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - create
      - delete
  - apiGroups:
      - ""
    resources:
      - endpoints
      - services
    verbs:
      - list
      - watch
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - kvm-operator-configmap
    verbs:
      - get
  - nonResourceURLs:
      - "/"
      - "/healthz"
    verbs:
      - get
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kvm-operator
subjects:
  - kind: ServiceAccount
    name: kvm-operator
    namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: kvm-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kvm-operator-psp
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    verbs:
      - use
    resourceNames:
      - kvm-operator-psp
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kvm-operator-psp
subjects:
  - kind: ServiceAccount
    name: kvm-operator
    namespace: giantswarm
roleRef:
  kind: ClusterRole
  name: kvm-operator-psp
  apiGroup: rbac.authorization.k8s.io