apiVersion: v1
kind: Service
metadata:
  name: cluster-controller
  namespace: giantswarm
  labels:
    app: cluster-controller
spec:
  type: NodePort
  ports:
  - port: 8000
  selector:
    app: cluster-controller
